// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Street address information for customers, employees, and vendors.
/// </summary>
[Table("address", Schema = "person")]
public partial class address
{
    /// <summary>
    /// Primary key for Address records.
    /// </summary>
    [Key]
    public int addressid { get; set; }

    /// <summary>
    /// First street address line.
    /// </summary>
    [Required]
    [StringLength(60)]
    public string addressline1 { get; set; }

    /// <summary>
    /// Second street address line.
    /// </summary>
    [StringLength(60)]
    public string addressline2 { get; set; }

    /// <summary>
    /// Name of the city.
    /// </summary>
    [Required]
    [StringLength(30)]
    public string city { get; set; }

    /// <summary>
    /// Unique identification number for the state or province. Foreign key to StateProvince table.
    /// </summary>
    public int stateprovinceid { get; set; }

    /// <summary>
    /// Postal code for the street address.
    /// </summary>
    [Required]
    [StringLength(15)]
    public string postalcode { get; set; }

    /// <summary>
    /// Latitude and longitude of this address.
    /// </summary>
    [StringLength(44)]
    public string spatiallocation { get; set; }

    public Guid rowguid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("address")]
    public virtual ICollection<businessentityaddress> businessentityaddresses { get; set; } = new List<businessentityaddress>();

    [InverseProperty("billtoaddress")]
    public virtual ICollection<salesorderheader> salesorderheaderbilltoaddresses { get; set; } = new List<salesorderheader>();

    [InverseProperty("shiptoaddress")]
    public virtual ICollection<salesorderheader> salesorderheadershiptoaddresses { get; set; } = new List<salesorderheader>();

    [ForeignKey("stateprovinceid")]
    [InverseProperty("addresses")]
    public virtual stateprovince stateprovince { get; set; }
}