// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Items required to make bicycles and bicycle subassemblies. It identifies the heirarchical relationship between a parent product and its components.
/// </summary>
[Table("billofmaterials", Schema = "production")]
public partial class billofmaterial
{
    /// <summary>
    /// Primary key for BillOfMaterials records.
    /// </summary>
    [Key]
    public int billofmaterialsid { get; set; }

    /// <summary>
    /// Parent product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int? productassemblyid { get; set; }

    /// <summary>
    /// Component identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int componentid { get; set; }

    /// <summary>
    /// Date the component started being used in the assembly item.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime startdate { get; set; }

    /// <summary>
    /// Date the component stopped being used in the assembly item.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? enddate { get; set; }

    /// <summary>
    /// Standard code identifying the unit of measure for the quantity.
    /// </summary>
    [Required]
    [StringLength(3)]
    public string unitmeasurecode { get; set; }

    /// <summary>
    /// Indicates the depth the component is from its parent (AssemblyID).
    /// </summary>
    public short bomlevel { get; set; }

    /// <summary>
    /// Quantity of the component needed to create the assembly.
    /// </summary>
    [Precision(8, 2)]
    public decimal perassemblyqty { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("componentid")]
    [InverseProperty("billofmaterialcomponents")]
    public virtual product component { get; set; }

    [ForeignKey("productassemblyid")]
    [InverseProperty("billofmaterialproductassemblies")]
    public virtual product productassembly { get; set; }

    [ForeignKey("unitmeasurecode")]
    [InverseProperty("billofmaterials")]
    public virtual unitmeasure unitmeasurecodeNavigation { get; set; }
}