// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Cross-reference table mapping customers, vendors, and employees to their addresses.
/// </summary>
[PrimaryKey("businessentityid", "addressid", "addresstypeid")]
[Table("businessentityaddress", Schema = "person")]
public partial class businessentityaddress
{
    /// <summary>
    /// Primary key. Foreign key to BusinessEntity.BusinessEntityID.
    /// </summary>
    [Key]
    public int businessentityid { get; set; }

    /// <summary>
    /// Primary key. Foreign key to Address.AddressID.
    /// </summary>
    [Key]
    public int addressid { get; set; }

    /// <summary>
    /// Primary key. Foreign key to AddressType.AddressTypeID.
    /// </summary>
    [Key]
    public int addresstypeid { get; set; }

    public Guid rowguid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("addressid")]
    [InverseProperty("businessentityaddresses")]
    public virtual address address { get; set; }

    [ForeignKey("addresstypeid")]
    [InverseProperty("businessentityaddresses")]
    public virtual addresstype addresstype { get; set; }

    [ForeignKey("businessentityid")]
    [InverseProperty("businessentityaddresses")]
    public virtual businessentity businessentity { get; set; }
}