// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Source of the ID that connects vendors, customers, and employees with address and contact information.
/// </summary>
[Table("businessentity", Schema = "person")]
public partial class businessentity
{
    /// <summary>
    /// Primary key for all customers, vendors, and employees.
    /// </summary>
    [Key]
    public int businessentityid { get; set; }

    public Guid rowguid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("businessentity")]
    public virtual ICollection<businessentityaddress> businessentityaddresses { get; set; } = new List<businessentityaddress>();

    [InverseProperty("businessentity")]
    public virtual ICollection<businessentitycontact> businessentitycontacts { get; set; } = new List<businessentitycontact>();

    [InverseProperty("businessentity")]
    public virtual person person { get; set; }

    [InverseProperty("businessentity")]
    public virtual store store { get; set; }

    [InverseProperty("businessentity")]
    public virtual vendor vendor { get; set; }
}