// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Lookup table containing the types of business entity contacts.
/// </summary>
[Table("contacttype", Schema = "person")]
public partial class contacttype
{
    /// <summary>
    /// Primary key for ContactType records.
    /// </summary>
    [Key]
    public int contacttypeid { get; set; }

    /// <summary>
    /// Contact type description.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string name { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("contacttype")]
    public virtual ICollection<businessentitycontact> businessentitycontacts { get; set; } = new List<businessentitycontact>();
}