// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Lookup table containing the ISO standard codes for countries and regions.
/// </summary>
[Table("countryregion", Schema = "person")]
public partial class countryregion
{
    /// <summary>
    /// ISO standard code for countries and regions.
    /// </summary>
    [Key]
    [StringLength(3)]
    public string countryregioncode { get; set; }

    /// <summary>
    /// Country or region name.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string name { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("countryregioncodeNavigation")]
    public virtual ICollection<countryregioncurrency> countryregioncurrencies { get; set; } = new List<countryregioncurrency>();

    [InverseProperty("countryregioncodeNavigation")]
    public virtual ICollection<salesterritory> salesterritories { get; set; } = new List<salesterritory>();

    [InverseProperty("countryregioncodeNavigation")]
    public virtual ICollection<stateprovince> stateprovinces { get; set; } = new List<stateprovince>();
}