// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Cross-reference table mapping ISO currency codes to a country or region.
/// </summary>
[PrimaryKey("countryregioncode", "currencycode")]
[Table("countryregioncurrency", Schema = "sales")]
public partial class countryregioncurrency
{
    /// <summary>
    /// ISO code for countries and regions. Foreign key to CountryRegion.CountryRegionCode.
    /// </summary>
    [Key]
    [StringLength(3)]
    public string countryregioncode { get; set; }

    /// <summary>
    /// ISO standard currency code. Foreign key to Currency.CurrencyCode.
    /// </summary>
    [Key]
    [StringLength(3)]
    public string currencycode { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("countryregioncode")]
    [InverseProperty("countryregioncurrencies")]
    public virtual countryregion countryregioncodeNavigation { get; set; }

    [ForeignKey("currencycode")]
    [InverseProperty("countryregioncurrencies")]
    public virtual currency currencycodeNavigation { get; set; }
}