// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Customer credit card information.
/// </summary>
[Table("creditcard", Schema = "sales")]
public partial class creditcard
{
    /// <summary>
    /// Primary key for CreditCard records.
    /// </summary>
    [Key]
    public int creditcardid { get; set; }

    /// <summary>
    /// Credit card name.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string cardtype { get; set; }

    /// <summary>
    /// Credit card number.
    /// </summary>
    [Required]
    [StringLength(25)]
    public string cardnumber { get; set; }

    /// <summary>
    /// Credit card expiration month.
    /// </summary>
    public short expmonth { get; set; }

    /// <summary>
    /// Credit card expiration year.
    /// </summary>
    public short expyear { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("creditcard")]
    public virtual ICollection<personcreditcard> personcreditcards { get; set; } = new List<personcreditcard>();

    [InverseProperty("creditcard")]
    public virtual ICollection<salesorderheader> salesorderheaders { get; set; } = new List<salesorderheader>();
}