// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Lookup table containing the languages in which some AdventureWorks data is stored.
/// </summary>
[Table("culture", Schema = "production")]
public partial class culture
{
    /// <summary>
    /// Primary key for Culture records.
    /// </summary>
    [Key]
    [StringLength(6)]
    public string cultureid { get; set; }

    /// <summary>
    /// Culture description.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string name { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("culture")]
    public virtual ICollection<productmodelproductdescriptionculture> productmodelproductdescriptioncultures { get; set; } = new List<productmodelproductdescriptionculture>();
}