// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Currency exchange rates.
/// </summary>
[Table("currencyrate", Schema = "sales")]
public partial class currencyrate
{
    /// <summary>
    /// Primary key for CurrencyRate records.
    /// </summary>
    [Key]
    public int currencyrateid { get; set; }

    /// <summary>
    /// Date and time the exchange rate was obtained.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime currencyratedate { get; set; }

    /// <summary>
    /// Exchange rate was converted from this currency code.
    /// </summary>
    [Required]
    [StringLength(3)]
    public string fromcurrencycode { get; set; }

    /// <summary>
    /// Exchange rate was converted to this currency code.
    /// </summary>
    [Required]
    [StringLength(3)]
    public string tocurrencycode { get; set; }

    /// <summary>
    /// Average exchange rate for the day.
    /// </summary>
    public decimal averagerate { get; set; }

    /// <summary>
    /// Final exchange rate for the day.
    /// </summary>
    public decimal endofdayrate { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("fromcurrencycode")]
    [InverseProperty("currencyratefromcurrencycodeNavigations")]
    public virtual currency fromcurrencycodeNavigation { get; set; }

    [InverseProperty("currencyrate")]
    public virtual ICollection<salesorderheader> salesorderheaders { get; set; } = new List<salesorderheader>();

    [ForeignKey("tocurrencycode")]
    [InverseProperty("currencyratetocurrencycodeNavigations")]
    public virtual currency tocurrencycodeNavigation { get; set; }
}