// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Lookup table containing standard ISO currencies.
/// </summary>
[Table("currency", Schema = "sales")]
public partial class currency
{
    /// <summary>
    /// The ISO code for the Currency.
    /// </summary>
    [Key]
    [StringLength(3)]
    public string currencycode { get; set; }

    /// <summary>
    /// Currency name.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string name { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("currencycodeNavigation")]
    public virtual ICollection<countryregioncurrency> countryregioncurrencies { get; set; } = new List<countryregioncurrency>();

    [InverseProperty("fromcurrencycodeNavigation")]
    public virtual ICollection<currencyrate> currencyratefromcurrencycodeNavigations { get; set; } = new List<currencyrate>();

    [InverseProperty("tocurrencycodeNavigation")]
    public virtual ICollection<currencyrate> currencyratetocurrencycodeNavigations { get; set; } = new List<currencyrate>();
}