// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Current customer information. Also see the Person and Store tables.
/// </summary>
[Table("customer", Schema = "sales")]
public partial class customer
{
    /// <summary>
    /// Primary key.
    /// </summary>
    [Key]
    public int customerid { get; set; }

    /// <summary>
    /// Foreign key to Person.BusinessEntityID
    /// </summary>
    public int? personid { get; set; }

    /// <summary>
    /// Foreign key to Store.BusinessEntityID
    /// </summary>
    public int? storeid { get; set; }

    /// <summary>
    /// ID of the territory in which the customer is located. Foreign key to SalesTerritory.SalesTerritoryID.
    /// </summary>
    public int? territoryid { get; set; }

    public Guid rowguid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("personid")]
    [InverseProperty("customers")]
    public virtual person person { get; set; }

    [InverseProperty("customer")]
    public virtual ICollection<salesorderheader> salesorderheaders { get; set; } = new List<salesorderheader>();

    [ForeignKey("storeid")]
    [InverseProperty("customers")]
    public virtual store store { get; set; }

    [ForeignKey("territoryid")]
    [InverseProperty("customers")]
    public virtual salesterritory territory { get; set; }
}