// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Lookup table containing the departments within the Adventure Works Cycles company.
/// </summary>
[Table("department", Schema = "humanresources")]
public partial class department
{
    /// <summary>
    /// Primary key for Department records.
    /// </summary>
    [Key]
    public int departmentid { get; set; }

    /// <summary>
    /// Name of the department.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string name { get; set; }

    /// <summary>
    /// Name of the group to which the department belongs.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string groupname { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("department")]
    public virtual ICollection<employeedepartmenthistory> employeedepartmenthistories { get; set; } = new List<employeedepartmenthistory>();
}