// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Where to send a person email.
/// </summary>
[PrimaryKey("businessentityid", "emailaddressid")]
[Table("emailaddress", Schema = "person")]
public partial class emailaddress
{
    /// <summary>
    /// Primary key. Person associated with this email address.  Foreign key to Person.BusinessEntityID
    /// </summary>
    [Key]
    public int businessentityid { get; set; }

    /// <summary>
    /// Primary key. ID of this email address.
    /// </summary>
    [Key]
    public int emailaddressid { get; set; }

    /// <summary>
    /// E-mail address for the person.
    /// </summary>
    [Column("emailaddress")]
    [StringLength(50)]
    public string emailaddress1 { get; set; }

    public Guid rowguid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("businessentityid")]
    [InverseProperty("emailaddresses")]
    public virtual person businessentity { get; set; }
}