// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Employee pay history.
/// </summary>
[PrimaryKey("businessentityid", "ratechangedate")]
[Table("employeepayhistory", Schema = "humanresources")]
public partial class employeepayhistory
{
    /// <summary>
    /// Employee identification number. Foreign key to Employee.BusinessEntityID.
    /// </summary>
    [Key]
    public int businessentityid { get; set; }

    /// <summary>
    /// Date the change in pay is effective
    /// </summary>
    [Key]
    [Column(TypeName = "timestamp without time zone")]
    public DateTime ratechangedate { get; set; }

    /// <summary>
    /// Salary hourly rate.
    /// </summary>
    public decimal rate { get; set; }

    /// <summary>
    /// 1 = Salary received monthly, 2 = Salary received biweekly
    /// </summary>
    public short payfrequency { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("businessentityid")]
    [InverseProperty("employeepayhistories")]
    public virtual employee businessentity { get; set; }
}