// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Employee department transfers.
/// </summary>
[PrimaryKey("businessentityid", "startdate", "departmentid", "shiftid")]
[Table("employeedepartmenthistory", Schema = "humanresources")]
public partial class employeedepartmenthistory
{
    /// <summary>
    /// Employee identification number. Foreign key to Employee.BusinessEntityID.
    /// </summary>
    [Key]
    public int businessentityid { get; set; }

    /// <summary>
    /// Department in which the employee worked including currently. Foreign key to Department.DepartmentID.
    /// </summary>
    [Key]
    public int departmentid { get; set; }

    /// <summary>
    /// Identifies which 8-hour shift the employee works. Foreign key to Shift.Shift.ID.
    /// </summary>
    [Key]
    public int shiftid { get; set; }

    /// <summary>
    /// Date the employee started work in the department.
    /// </summary>
    [Key]
    public DateOnly startdate { get; set; }

    /// <summary>
    /// Date the employee left the department. NULL = Current department.
    /// </summary>
    public DateOnly? enddate { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("businessentityid")]
    [InverseProperty("employeedepartmenthistories")]
    public virtual employee businessentity { get; set; }

    [ForeignKey("departmentid")]
    [InverseProperty("employeedepartmenthistories")]
    public virtual department department { get; set; }

    [ForeignKey("shiftid")]
    [InverseProperty("employeedepartmenthistories")]
    public virtual shift shift { get; set; }
}