// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// RÃ©sumÃ©s submitted to Human Resources by job applicants.
/// </summary>
[Table("jobcandidate", Schema = "humanresources")]
public partial class jobcandidate
{
    /// <summary>
    /// Primary key for JobCandidate records.
    /// </summary>
    [Key]
    public int jobcandidateid { get; set; }

    /// <summary>
    /// Employee identification number if applicant was hired. Foreign key to Employee.BusinessEntityID.
    /// </summary>
    public int? businessentityid { get; set; }

    /// <summary>
    /// RÃ©sumÃ© in XML format.
    /// </summary>
    [Column(TypeName = "xml")]
    public string resume { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("businessentityid")]
    [InverseProperty("jobcandidates")]
    public virtual employee businessentity { get; set; }
}