// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// One way hashed authentication information
/// </summary>
[Table("password", Schema = "person")]
public partial class password
{
    [Key]
    public int businessentityid { get; set; }

    /// <summary>
    /// Password for the e-mail account.
    /// </summary>
    [Required]
    [StringLength(128)]
    public string passwordhash { get; set; }

    /// <summary>
    /// Random value concatenated with the password string before the password is hashed.
    /// </summary>
    [Required]
    [StringLength(10)]
    public string passwordsalt { get; set; }

    public Guid rowguid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("businessentityid")]
    [InverseProperty("password")]
    public virtual person businessentity { get; set; }
}