// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Cross-reference table mapping people to their credit card information in the CreditCard table.
/// </summary>
[PrimaryKey("businessentityid", "creditcardid")]
[Table("personcreditcard", Schema = "sales")]
public partial class personcreditcard
{
    /// <summary>
    /// Business entity identification number. Foreign key to Person.BusinessEntityID.
    /// </summary>
    [Key]
    public int businessentityid { get; set; }

    /// <summary>
    /// Credit card identification number. Foreign key to CreditCard.CreditCardID.
    /// </summary>
    [Key]
    public int creditcardid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("businessentityid")]
    [InverseProperty("personcreditcards")]
    public virtual person businessentity { get; set; }

    [ForeignKey("creditcardid")]
    [InverseProperty("personcreditcards")]
    public virtual creditcard creditcard { get; set; }
}