// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Telephone number and type of a person.
/// </summary>
[PrimaryKey("businessentityid", "phonenumber", "phonenumbertypeid")]
[Table("personphone", Schema = "person")]
public partial class personphone
{
    /// <summary>
    /// Business entity identification number. Foreign key to Person.BusinessEntityID.
    /// </summary>
    [Key]
    public int businessentityid { get; set; }

    /// <summary>
    /// Telephone number identification number.
    /// </summary>
    [Key]
    [StringLength(25)]
    public string phonenumber { get; set; }

    /// <summary>
    /// Kind of phone number. Foreign key to PhoneNumberType.PhoneNumberTypeID.
    /// </summary>
    [Key]
    public int phonenumbertypeid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("businessentityid")]
    [InverseProperty("personphones")]
    public virtual person businessentity { get; set; }

    [ForeignKey("phonenumbertypeid")]
    [InverseProperty("personphones")]
    public virtual phonenumbertype phonenumbertype { get; set; }
}