// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Type of phone number of a person.
/// </summary>
[Table("phonenumbertype", Schema = "person")]
public partial class phonenumbertype
{
    /// <summary>
    /// Primary key for telephone number type records.
    /// </summary>
    [Key]
    public int phonenumbertypeid { get; set; }

    /// <summary>
    /// Name of the telephone number type
    /// </summary>
    [Required]
    [StringLength(50)]
    public string name { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("phonenumbertype")]
    public virtual ICollection<personphone> personphones { get; set; } = new List<personphone>();
}