// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Product images.
/// </summary>
[Table("productphoto", Schema = "production")]
public partial class productphoto
{
    /// <summary>
    /// Primary key for ProductPhoto records.
    /// </summary>
    [Key]
    public int productphotoid { get; set; }

    /// <summary>
    /// Small image of the product.
    /// </summary>
    public byte[] thumbnailphoto { get; set; }

    /// <summary>
    /// Small image file name.
    /// </summary>
    [StringLength(50)]
    public string thumbnailphotofilename { get; set; }

    /// <summary>
    /// Large image of the product.
    /// </summary>
    public byte[] largephoto { get; set; }

    /// <summary>
    /// Large image file name.
    /// </summary>
    [StringLength(50)]
    public string largephotofilename { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("productphoto")]
    public virtual ICollection<productproductphoto> productproductphotos { get; set; } = new List<productproductphoto>();
}