// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Cross-reference table mapping product descriptions and the language the description is written in.
/// </summary>
[PrimaryKey("productmodelid", "productdescriptionid", "cultureid")]
[Table("productmodelproductdescriptionculture", Schema = "production")]
public partial class productmodelproductdescriptionculture
{
    /// <summary>
    /// Primary key. Foreign key to ProductModel.ProductModelID.
    /// </summary>
    [Key]
    public int productmodelid { get; set; }

    /// <summary>
    /// Primary key. Foreign key to ProductDescription.ProductDescriptionID.
    /// </summary>
    [Key]
    public int productdescriptionid { get; set; }

    /// <summary>
    /// Culture identification number. Foreign key to Culture.CultureID.
    /// </summary>
    [Key]
    [StringLength(6)]
    public string cultureid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("cultureid")]
    [InverseProperty("productmodelproductdescriptioncultures")]
    public virtual culture culture { get; set; }

    [ForeignKey("productdescriptionid")]
    [InverseProperty("productmodelproductdescriptioncultures")]
    public virtual productdescription productdescription { get; set; }

    [ForeignKey("productmodelid")]
    [InverseProperty("productmodelproductdescriptioncultures")]
    public virtual productmodel productmodel { get; set; }
}