// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Changes in the list price of a product over time.
/// </summary>
[PrimaryKey("productid", "startdate")]
[Table("productlistpricehistory", Schema = "production")]
public partial class productlistpricehistory
{
    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID
    /// </summary>
    [Key]
    public int productid { get; set; }

    /// <summary>
    /// List price start date.
    /// </summary>
    [Key]
    [Column(TypeName = "timestamp without time zone")]
    public DateTime startdate { get; set; }

    /// <summary>
    /// List price end date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? enddate { get; set; }

    /// <summary>
    /// Product list price.
    /// </summary>
    public decimal listprice { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("productid")]
    [InverseProperty("productlistpricehistories")]
    public virtual product product { get; set; }
}