// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Cross-reference table mapping product models and illustrations.
/// </summary>
[PrimaryKey("productmodelid", "illustrationid")]
[Table("productmodelillustration", Schema = "production")]
public partial class productmodelillustration
{
    /// <summary>
    /// Primary key. Foreign key to ProductModel.ProductModelID.
    /// </summary>
    [Key]
    public int productmodelid { get; set; }

    /// <summary>
    /// Primary key. Foreign key to Illustration.IllustrationID.
    /// </summary>
    [Key]
    public int illustrationid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("illustrationid")]
    [InverseProperty("productmodelillustrations")]
    public virtual illustration illustration { get; set; }

    [ForeignKey("productmodelid")]
    [InverseProperty("productmodelillustrations")]
    public virtual productmodel productmodel { get; set; }
}