// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Customer reviews of products they have purchased.
/// </summary>
[Table("productreview", Schema = "production")]
public partial class productreview
{
    /// <summary>
    /// Primary key for ProductReview records.
    /// </summary>
    [Key]
    public int productreviewid { get; set; }

    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int productid { get; set; }

    /// <summary>
    /// Name of the reviewer.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string reviewername { get; set; }

    /// <summary>
    /// Date review was submitted.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime reviewdate { get; set; }

    /// <summary>
    /// Reviewer&apos;s e-mail address.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string emailaddress { get; set; }

    /// <summary>
    /// Product rating given by the reviewer. Scale is 1 to 5 with 5 as the highest rating.
    /// </summary>
    public int rating { get; set; }

    /// <summary>
    /// Reviewer&apos;s comments
    /// </summary>
    [StringLength(3850)]
    public string comments { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("productid")]
    [InverseProperty("productreviews")]
    public virtual product product { get; set; }
}