// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Cross-reference table mapping products to related product documents.
/// </summary>
[PrimaryKey("productid", "documentnode")]
[Table("productdocument", Schema = "production")]
public partial class productdocument
{
    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    [Key]
    public int productid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    /// <summary>
    /// Document identification number. Foreign key to Document.DocumentNode.
    /// </summary>
    [Key]
    [Column(TypeName = "character varying")]
    public string documentnode { get; set; }

    [ForeignKey("documentnode")]
    [InverseProperty("productdocuments")]
    public virtual document documentnodeNavigation { get; set; }

    [ForeignKey("productid")]
    [InverseProperty("productdocuments")]
    public virtual product product { get; set; }
}