// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// General purchase order information. See PurchaseOrderDetail.
/// </summary>
[Table("purchaseorderheader", Schema = "purchasing")]
public partial class purchaseorderheader
{
    /// <summary>
    /// Primary key.
    /// </summary>
    [Key]
    public int purchaseorderid { get; set; }

    /// <summary>
    /// Incremental number to track changes to the purchase order over time.
    /// </summary>
    public short revisionnumber { get; set; }

    /// <summary>
    /// Order current status. 1 = Pending; 2 = Approved; 3 = Rejected; 4 = Complete
    /// </summary>
    public short status { get; set; }

    /// <summary>
    /// Employee who created the purchase order. Foreign key to Employee.BusinessEntityID.
    /// </summary>
    public int employeeid { get; set; }

    /// <summary>
    /// Vendor with whom the purchase order is placed. Foreign key to Vendor.BusinessEntityID.
    /// </summary>
    public int vendorid { get; set; }

    /// <summary>
    /// Shipping method. Foreign key to ShipMethod.ShipMethodID.
    /// </summary>
    public int shipmethodid { get; set; }

    /// <summary>
    /// Purchase order creation date.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime orderdate { get; set; }

    /// <summary>
    /// Estimated shipment date from the vendor.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? shipdate { get; set; }

    /// <summary>
    /// Purchase order subtotal. Computed as SUM(PurchaseOrderDetail.LineTotal)for the appropriate PurchaseOrderID.
    /// </summary>
    public decimal subtotal { get; set; }

    /// <summary>
    /// Tax amount.
    /// </summary>
    public decimal taxamt { get; set; }

    /// <summary>
    /// Shipping cost.
    /// </summary>
    public decimal freight { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("employeeid")]
    [InverseProperty("purchaseorderheaders")]
    public virtual employee employee { get; set; }

    [InverseProperty("purchaseorder")]
    public virtual ICollection<purchaseorderdetail> purchaseorderdetails { get; set; } = new List<purchaseorderdetail>();

    [ForeignKey("shipmethodid")]
    [InverseProperty("purchaseorderheaders")]
    public virtual shipmethod shipmethod { get; set; }

    [ForeignKey("vendorid")]
    [InverseProperty("purchaseorderheaders")]
    public virtual vendor vendor { get; set; }
}