// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Individual products associated with a specific sales order. See SalesOrderHeader.
/// </summary>
[PrimaryKey("salesorderid", "salesorderdetailid")]
[Table("salesorderdetail", Schema = "sales")]
public partial class salesorderdetail
{
    /// <summary>
    /// Primary key. Foreign key to SalesOrderHeader.SalesOrderID.
    /// </summary>
    [Key]
    public int salesorderid { get; set; }

    /// <summary>
    /// Primary key. One incremental unique number per product sold.
    /// </summary>
    [Key]
    public int salesorderdetailid { get; set; }

    /// <summary>
    /// Shipment tracking number supplied by the shipper.
    /// </summary>
    [StringLength(25)]
    public string carriertrackingnumber { get; set; }

    /// <summary>
    /// Quantity ordered per product.
    /// </summary>
    public short orderqty { get; set; }

    /// <summary>
    /// Product sold to customer. Foreign key to Product.ProductID.
    /// </summary>
    public int productid { get; set; }

    /// <summary>
    /// Promotional code. Foreign key to SpecialOffer.SpecialOfferID.
    /// </summary>
    public int specialofferid { get; set; }

    /// <summary>
    /// Selling price of a single product.
    /// </summary>
    public decimal unitprice { get; set; }

    /// <summary>
    /// Discount amount.
    /// </summary>
    public decimal unitpricediscount { get; set; }

    public Guid rowguid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("salesorderid")]
    [InverseProperty("salesorderdetails")]
    public virtual salesorderheader salesorder { get; set; }

    [ForeignKey("specialofferid, productid")]
    [InverseProperty("salesorderdetails")]
    public virtual specialofferproduct specialofferproduct { get; set; }
}