// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Tax rate lookup table.
/// </summary>
[Table("salestaxrate", Schema = "sales")]
public partial class salestaxrate
{
    /// <summary>
    /// Primary key for SalesTaxRate records.
    /// </summary>
    [Key]
    public int salestaxrateid { get; set; }

    /// <summary>
    /// State, province, or country/region the sales tax applies to.
    /// </summary>
    public int stateprovinceid { get; set; }

    /// <summary>
    /// 1 = Tax applied to retail transactions, 2 = Tax applied to wholesale transactions, 3 = Tax applied to all sales (retail and wholesale) transactions.
    /// </summary>
    public short taxtype { get; set; }

    /// <summary>
    /// Tax rate amount.
    /// </summary>
    public decimal taxrate { get; set; }

    /// <summary>
    /// Tax rate description.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string name { get; set; }

    public Guid rowguid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("stateprovinceid")]
    [InverseProperty("salestaxrates")]
    public virtual stateprovince stateprovince { get; set; }
}