// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Cross-reference table mapping sales orders to sales reason codes.
/// </summary>
[PrimaryKey("salesorderid", "salesreasonid")]
[Table("salesorderheadersalesreason", Schema = "sales")]
public partial class salesorderheadersalesreason
{
    /// <summary>
    /// Primary key. Foreign key to SalesOrderHeader.SalesOrderID.
    /// </summary>
    [Key]
    public int salesorderid { get; set; }

    /// <summary>
    /// Primary key. Foreign key to SalesReason.SalesReasonID.
    /// </summary>
    [Key]
    public int salesreasonid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("salesorderid")]
    [InverseProperty("salesorderheadersalesreasons")]
    public virtual salesorderheader salesorder { get; set; }

    [ForeignKey("salesreasonid")]
    [InverseProperty("salesorderheadersalesreasons")]
    public virtual salesreason salesreason { get; set; }
}