// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Lookup table of customer purchase reasons.
/// </summary>
[Table("salesreason", Schema = "sales")]
public partial class salesreason
{
    /// <summary>
    /// Primary key for SalesReason records.
    /// </summary>
    [Key]
    public int salesreasonid { get; set; }

    /// <summary>
    /// Sales reason description.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string name { get; set; }

    /// <summary>
    /// Category the sales reason belongs to.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string reasontype { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("salesreason")]
    public virtual ICollection<salesorderheadersalesreason> salesorderheadersalesreasons { get; set; } = new List<salesorderheadersalesreason>();
}