// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Manufacturing failure reasons lookup table.
/// </summary>
[Table("scrapreason", Schema = "production")]
public partial class scrapreason
{
    /// <summary>
    /// Primary key for ScrapReason records.
    /// </summary>
    [Key]
    public int scrapreasonid { get; set; }

    /// <summary>
    /// Failure description.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string name { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("scrapreason")]
    public virtual ICollection<workorder> workorders { get; set; } = new List<workorder>();
}