// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Work shift lookup table.
/// </summary>
[Table("shift", Schema = "humanresources")]
public partial class shift
{
    /// <summary>
    /// Primary key for Shift records.
    /// </summary>
    [Key]
    public int shiftid { get; set; }

    /// <summary>
    /// Shift description.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string name { get; set; }

    /// <summary>
    /// Shift start time.
    /// </summary>
    public TimeOnly starttime { get; set; }

    /// <summary>
    /// Shift end time.
    /// </summary>
    public TimeOnly endtime { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("shift")]
    public virtual ICollection<employeedepartmenthistory> employeedepartmenthistories { get; set; } = new List<employeedepartmenthistory>();
}