// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Shipping company lookup table.
/// </summary>
[Table("shipmethod", Schema = "purchasing")]
public partial class shipmethod
{
    /// <summary>
    /// Primary key for ShipMethod records.
    /// </summary>
    [Key]
    public int shipmethodid { get; set; }

    /// <summary>
    /// Shipping company name.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string name { get; set; }

    /// <summary>
    /// Minimum shipping charge.
    /// </summary>
    public decimal shipbase { get; set; }

    /// <summary>
    /// Shipping charge per pound.
    /// </summary>
    public decimal shiprate { get; set; }

    public Guid rowguid { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [InverseProperty("shipmethod")]
    public virtual ICollection<purchaseorderheader> purchaseorderheaders { get; set; } = new List<purchaseorderheader>();

    [InverseProperty("shipmethod")]
    public virtual ICollection<salesorderheader> salesorderheaders { get; set; } = new List<salesorderheader>();
}