// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Contains online customer orders until the order is submitted or cancelled.
/// </summary>
[Table("shoppingcartitem", Schema = "sales")]
public partial class shoppingcartitem
{
    /// <summary>
    /// Primary key for ShoppingCartItem records.
    /// </summary>
    [Key]
    public int shoppingcartitemid { get; set; }

    /// <summary>
    /// Shopping cart identification number.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string shoppingcartid { get; set; }

    /// <summary>
    /// Product quantity ordered.
    /// </summary>
    public int quantity { get; set; }

    /// <summary>
    /// Product ordered. Foreign key to Product.ProductID.
    /// </summary>
    public int productid { get; set; }

    /// <summary>
    /// Date the time the record was created.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime datecreated { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("productid")]
    [InverseProperty("shoppingcartitems")]
    public virtual product product { get; set; }
}