// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Record of each purchase order, sales order, or work order transaction year to date.
/// </summary>
[Table("transactionhistory", Schema = "production")]
public partial class transactionhistory
{
    /// <summary>
    /// Primary key for TransactionHistory records.
    /// </summary>
    [Key]
    public int transactionid { get; set; }

    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int productid { get; set; }

    /// <summary>
    /// Purchase order, sales order, or work order identification number.
    /// </summary>
    public int referenceorderid { get; set; }

    /// <summary>
    /// Line number associated with the purchase order, sales order, or work order.
    /// </summary>
    public int referenceorderlineid { get; set; }

    /// <summary>
    /// Date and time of the transaction.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime transactiondate { get; set; }

    /// <summary>
    /// W = WorkOrder, S = SalesOrder, P = PurchaseOrder
    /// </summary>
    [MaxLength(1)]
    public string transactiontype { get; set; }

    /// <summary>
    /// Product quantity.
    /// </summary>
    public int quantity { get; set; }

    /// <summary>
    /// Product cost.
    /// </summary>
    public decimal actualcost { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("productid")]
    [InverseProperty("transactionhistories")]
    public virtual product product { get; set; }
}