// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Transactions for previous years.
/// </summary>
[Table("transactionhistoryarchive", Schema = "production")]
public partial class transactionhistoryarchive
{
    /// <summary>
    /// Primary key for TransactionHistoryArchive records.
    /// </summary>
    [Key]
    public int transactionid { get; set; }

    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int productid { get; set; }

    /// <summary>
    /// Purchase order, sales order, or work order identification number.
    /// </summary>
    public int referenceorderid { get; set; }

    /// <summary>
    /// Line number associated with the purchase order, sales order, or work order.
    /// </summary>
    public int referenceorderlineid { get; set; }

    /// <summary>
    /// Date and time of the transaction.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime transactiondate { get; set; }

    /// <summary>
    /// W = Work Order, S = Sales Order, P = Purchase Order
    /// </summary>
    [MaxLength(1)]
    public string transactiontype { get; set; }

    /// <summary>
    /// Product quantity.
    /// </summary>
    public int quantity { get; set; }

    /// <summary>
    /// Product cost.
    /// </summary>
    public decimal actualcost { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }
}