// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace repository.Models;

/// <summary>
/// Work order details.
/// </summary>
[PrimaryKey("workorderid", "productid", "operationsequence")]
[Table("workorderrouting", Schema = "production")]
public partial class workorderrouting
{
    /// <summary>
    /// Primary key. Foreign key to WorkOrder.WorkOrderID.
    /// </summary>
    [Key]
    public int workorderid { get; set; }

    /// <summary>
    /// Primary key. Foreign key to Product.ProductID.
    /// </summary>
    [Key]
    public int productid { get; set; }

    /// <summary>
    /// Primary key. Indicates the manufacturing process sequence.
    /// </summary>
    [Key]
    public short operationsequence { get; set; }

    /// <summary>
    /// Manufacturing location where the part is processed. Foreign key to Location.LocationID.
    /// </summary>
    public int locationid { get; set; }

    /// <summary>
    /// Planned manufacturing start date.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime scheduledstartdate { get; set; }

    /// <summary>
    /// Planned manufacturing end date.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime scheduledenddate { get; set; }

    /// <summary>
    /// Actual start date.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? actualstartdate { get; set; }

    /// <summary>
    /// Actual end date.
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime? actualenddate { get; set; }

    /// <summary>
    /// Number of manufacturing hours used.
    /// </summary>
    [Precision(9, 4)]
    public decimal? actualresourcehrs { get; set; }

    /// <summary>
    /// Estimated manufacturing cost.
    /// </summary>
    public decimal plannedcost { get; set; }

    /// <summary>
    /// Actual manufacturing cost.
    /// </summary>
    public decimal? actualcost { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime modifieddate { get; set; }

    [ForeignKey("locationid")]
    [InverseProperty("workorderroutings")]
    public virtual location location { get; set; }

    [ForeignKey("workorderid")]
    [InverseProperty("workorderroutings")]
    public virtual workorder workorder { get; set; }
}